### ISSUE TITLE
Tried to overwrite a file owned by another mod

### ISSUE THREAD

**Issue by websterhamster** [KSP-CKAN/CKAN-meta#676]
When attempting to update Solver Engines, it gives me this error.

File           : GameData/SolverEngines/SolverEngines.version
Installing Mod : SolverEngines v1.5
Owning Mod     : ModuleAnimateEmissive
CKAN Version   : v1.10.0-0-gb447380 (beta)

**Comment by dbent** [comment]
Fix implemented in KSP-CKAN/NetKAN#1835. Should be resolved in the next run of the bot in a few hours.

**Comment by dbent** [comment]
This should now be resolved, thanks.

**Comment by websterhamster** [comment]
Just thought I'd mention that it's still throwing the same error.

**Comment by plague006** [comment]
This might not be the most satisfying answer: but I just tested and had no issue. Can you try uninstalling SolverEngines and ModuleAnimateEmissive and re-installing?

**Comment by websterhamster** [comment]
That seems to have worked, thanks.
